version: "3"
services:
  
  db :
    image : postgres:11.7
    ports : 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pms
    volumes:
      - ./db/export:/db/export