apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
  namespace: default
spec:
  httpPipeline:
    handlers:
    #  - name: sentinel
    #    type: middleware.http.sentinel
      - name: ratelimit
        type: middleware.http.ratelimit