apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub
spec:
  topic: ORDER
  #route: /e/order-created
  pubsubname: pubsub 
  routes:
    rules:
      - match: event.type == "RestaurantOperationalTimingChanged"
        path: /restaurant/operational/timing
    default: /e/order-created
scopes:
- restaurant-service