apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub
spec:
  topic: ORDER
  #route: /restaurant
  pubsubname: pubsub 
  routes:
    rules:
      - match: event.type == "OrderCancelled"
        path: /e/order-cancelled
    default: /e/order-created
scopes:
- point-service